blank_issues_enabled: true
contact_links:
  - name: Discussion Notion
    url: https://www.notion.so/syncrobotic/2688e4b6282d81888ef7e493c2d4b7b8?source=copy_link
    about: 如果有一般性問題或討論，請使用 Notion 討論
