name: Feature Request
description: 提出新功能或改進建議
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        感謝你提出功能建議！
  
  - type: checkboxes
    attributes:
      label: 確認事項
      options:
        - label: 我已搜尋過現有的 Issues，確認沒有重複的建議
          required: true
  
  - type: textarea
    id: problem
    attributes:
      label: 問題或需求
      description: 描述你想解決的問題或需求
      placeholder: 我希望能夠...
    validations:
      required: true
  
  - type: textarea
    id: solution
    attributes:
      label: 建議的解決方案
      description: 描述你期望的功能或實作方式
    validations:
      required: true
  
  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案
      description: 你是否考慮過其他替代方案？
    validations:
      required: false
  
  - type: textarea
    id: additional
    attributes:
      label: 其他補充
      description: 任何其他相關資訊、截圖、參考連結等
    validations:
      required: false
